### ISSUE TITLE
Show gps info on hk page.

### ISSUE THREAD

**Issue by sylarcp** [sylarcp/anita#19]
gps panel contains :
1.location  (3 vector)
2.orientation (3 vector)
3. velocity

Also show the time and now.

**Comment by varriaza** [comment]
Hey Peng, I was wondering how I should construct the def get_adu5_nows(ip_db) [in the adu5.py file] as adu5 has three components (pat, vtg and sat). I figure it will probably be similar to how we used json_comments for each of the three types but I am unfamiliar with the nows function and what exactly it returns. But then does that mean we have to update each of them in the hk.html? Also, should we rewrite adu5 to use nbufs now that the others are not using them? Thanks!

**Comment by sylarcp** [comment]
First just implement adu5_pat, which have location and orientation information.
I will think about  how to  add other adu5 packets.

**Comment by varriaza** [comment]
Ok, thanks for the help and clarification.

**Comment by sylarcp** [comment]
And the adu5.py should be changed. Use nbuf to get a adu5 packet. The example is in hk.py.
