### ISSUE TITLE
phi view for waveforms

### ISSUE THREAD

**Issue by sylarcp** [sylarcp/anita#38]
The setting button on wv panel should contains two rows. 
First row is the radio buttons for voltage, fft and power.
Second row is radio buttons for Surf View and Phi View.
Also try to fix the radio button style.

For the Phi View, you will need a separate table located under Surf Table. When you click Phi, just hide the Surf View table. Vice versa. 
the layout of Phi View should be:
![image](https://cloud.githubusercontent.com/assets/15389620/16880957/6a7db8fa-4a7d-11e6-8d19-c137a23b725f.png)
The mapping documentation for ANITA3 is :
struct SurfMapType{
  int h_surf;
  int h_chan;
  int v_surf;
  int v_chan;
  int phi;
};
struct SurfMapType surfMap[]={
{ 12 , 8 , 12 , 4 , 1 },
{ 11 , 8 , 11 , 4 , 3 },
{ 12 , 6 , 12 , 2 , 5 },
{ 11 , 6 , 11 , 2 , 7 },
{ 12 , 7 , 12 , 3 , 9 },
{ 11 , 7 , 11 , 3 , 11 },
{ 12 , 5 , 12 , 1 , 13 },
{ 11 , 5 , 11 , 1 , 15 },
{ 6 , 6 , 6 , 2 , 2 },
{ 5 , 2 , 5 , 6 , 4 },
{ 5 , 8 , 5 , 4 , 6 },
{ 6 , 8 , 6 , 4 , 8 },
{ 6 , 5 , 6 , 1 , 10 },
{ 5 , 5 , 5 , 1 , 12 },
{ 5 , 7 , 5 , 3 , 14 },
{ 6 , 7 , 6 , 3 , 16 },
{ 10 , 6 , 10 , 2 , 1 },
{ 4 , 8 , 4 , 4 , 2 },
{ 9 , 6 , 9 , 2 , 3 },
{ 3 , 8 , 3 , 4 , 4 },
{ 9 , 8 , 9 , 4 , 5 },
{ 4 , 6 , 4 , 2 , 6 },
{ 10 , 8 , 10 , 4 , 7 },
{ 3 , 6 , 3 , 2 , 8 },
{ 10 , 5 , 10 , 1 , 9 },
{ 4 , 7 , 4 , 3 , 10 },
{ 9 , 5 , 9 , 1 , 11 },
{ 3 , 7 , 3 , 3 , 12 },
{ 9 , 7 , 9 , 3 , 13 },
{ 4 , 5 , 4 , 1 , 14 },
{ 10 , 7 , 10 , 3 , 15 },
{ 3 , 5 , 3 , 1 , 16 },
{ 7 , 8 , 7 , 4 , 1 },
{ 1 , 6 , 1 , 2 , 2 },
{ 8 , 8 , 8 , 4 , 3 },
{ 2 , 6 , 2 , 2 , 4 },
{ 7 , 6 , 7 , 2 , 5 },
{ 2 , 8 , 2 , 4 , 6 },
{ 8 , 6 , 8 , 2 , 7 },
{ 1 , 8 , 1 , 4 , 8 },
{ 7 , 7 , 7 , 3 , 9 },
{ 1 , 5 , 1 , 1 , 10 },
{ 8 , 7 , 8 , 3 , 11 },
{ 2 , 5 , 2 , 1 , 12 },
{ 7 , 5 , 7 , 1 , 13 },
{ 2 , 7 , 2 , 3 , 14 },
{ 8 , 5 , 8 , 1 , 15 },
{ 1 , 7 , 1 , 3 , 16 }
};
Let me know if it is not clear.

**Comment by varriaza** [comment]
Should the commands for mV, FFT and Power also apply to the Phi view page or are they limited to working on the surf view?

**Comment by dseckel** [comment]
all formats

**Comment by varriaza** [comment]
Ok, thanks!

**Comment by mcollins12321** [comment]
Could you elaborate the documentation and how we're getting data for the phi table?  Victor and I are having a hard time making sense of it.

**Comment by dseckel** [comment]
hi matt,

don't know if peng is on line, so i'll put in my two cents.

the display needs to have 16 phi sectors, with a top, middle and bottom antenna for each 
sector. each antenna has a Vertical and Horizontal feed. so all together there are

16_3_2 = 96 waveforms

the same 96 waveforms to be found in 12 surfs each with 8 channels.

all you need is a map ...

So my advice is produce the display using an adhoc map of your choice. later you can 
change the map when we get more info from peng or the anita 4 developers.

On another note - if you guys are in the building, can we get together around 4:00? I 
won't be around tomorrow.

dave

**Comment by mcollins12321** [comment]
We had the same idea, we're implementing now and plan on going home at 1:30.  If you want to meet at 4 we can come back to the building, but we feel like we haven't finished enough since Friday to warrant a meeting today.  Friday would be best for us.

**Comment by dseckel** [comment]
how about meeting with me for 5-10 minutes before you leave. i should be in my office at 
1:25.

**Comment by varriaza** [comment]
OK, that sounds good.

**Comment by sylarcp** [comment]
You need to show this 8*16 table. Each items is a waveform except there are some blanks.
![image](https://cloud.githubusercontent.com/assets/15389620/17000756/b51de3de-4e89-11e6-8ccd-c0913003cd0f.png)
There are 48 antennas in black color.  The number on the top is phi sector from 1 to 16. For each antenna,  the top one is H pol and the bottom one is V pol. So with the antenna number and polarization type you need to find the surf_num and chan_num and then calculate the id of waveform.

To find the id:
surfMap have 48 tuples,  corresponding to 48 antennas.
{ 12 , 8 , 12 , 4 , 1 }, is the first antenna and { 11 , 8 , 11 , 4 , 3 } is the second antenna and so on. Each antenna has H and V polarization waveforms, each waveform need surf_num and chan_num to be identified.
The meaning of  { 12 , 8 , 12 , 4 , 1 } is  { h_surf= 12 , h_chan= 8 , v_surf= 12 , v_chan=4 , phi=1 }.
Remember for each waveform in current wv panel there are surf_num and chan_num, and "var id = chan + 9*surf;" is used to determine the waveform id.

**Comment by varriaza** [comment]
Matt and I were wondering where exactly the surfMapType arrays were located so that we could hook them up to the code. Would the anita 3 documentation help us (as you referenced it) and if so could we have it?

**Comment by sylarcp** [comment]
Nope, the array is from the cpp code for old anitaviewer.  You need to create new array in Javascript.

**Comment by varriaza** [comment]
So the array you gave us is the full mapping array that we should put into the javascript on the page?

**Comment by sylarcp** [comment]
Yes, but be careful with format. They are cpp struct. You need javascript array.

**Comment by varriaza** [comment]
Right, thanks for the clarification!
