### ISSUE TITLE
align the panel boxes in slowmo page.

### ISSUE THREAD

**Issue by sylarcp** [sylarcp/anita#4]
avgscaler panel box should be next below the rfpower panel. There is too much space now.
![image](https://cloud.githubusercontent.com/assets/15389620/15834331/04ec980a-2bf9-11e6-9b1a-d71e6ced3154.png)

**Comment by varriaza** [comment]
If you really don't want the buttons in the header, I was wondering what made you come to that choice? When I added them to the base file and took out the existing buttons, everything worked perfectly and I thought it looked very nice. I figure if a page didn't want them, it doesn't have to extend the base file, right?

**Comment by sylarcp** [comment]
The base.html is the common parts for slowmo.html, aview.html and trigmon.html. Everything in the header should be in base.html.
   Next and prev is the buttons we have now but they are not enough. We  will add more buttons such last and auto. It seems not good to put all those buttons in the header.
Thanks.

**Comment by sylarcp** [comment]
Would you show me a screenshot of how it looks like?

**Comment by varriaza** [comment]
Sure, here are two pictures showing what it would look like in a small window and in a big (full screen) window.
![capture - small window](https://cloud.githubusercontent.com/assets/14185176/15871504/ee1942fc-2cc2-11e6-88d7-e3f0499ad50d.JPG)
![capture - full screen](https://cloud.githubusercontent.com/assets/14185176/15871516/02a560ac-2cc3-11e6-9212-c7309e97330a.JPG)
